region: eu-west-2
timeout: 10
deploymentBucket:
  blockPublicAccess: true
logRetentionInDays: 1
memorySize: 256
vpc:
  securityGroupIds:
    - ${cf:panic-system-infrastructure.VpcSecurityGroupId}
  subnetIds:
    - ${cf:panic-system-infrastructure.VpcSubnetAId}
    - ${cf:panic-system-infrastructure.VpcSubnetBId}
    - ${cf:panic-system-infrastructure.VpcSubnetCId}

httpApi:
  disableDefaultEndpoint: false
  authorizers:
    CognitoJwtAuthorizer:
      type: jwt
      identitySource: $request.header.Authorization
      issuerUrl: https://cognito-idp.eu-west-2.amazonaws.com/${cf:panic-system-infrastructure.CognitoUserPoolId} 
      audience:
        - ${cf:panic-system-infrastructure.CognitoUserPoolClientId} 
  cors: true
